### ISSUE TITLE
title is not available in your Netflix region

### ISSUE THREAD

**Issue by AbyssMorgan** [Divxeas/Netflix-videos-downloader1#1]
command:
```
NFripper.py "https://www.netflix.com/watch/81424207" --ns --high --alang Polish
```
output:
```
Getting Metadata...
title is not available in your Netflix region.
```

script stopped working for now

**Comment by AbyssMorgan** [comment]
after find this message in code i add resp.status_code and i got http error 404 but link is ok

**Comment by Aijima** [comment]
> 

ck is error !

**Comment by Aijima** [comment]
> after find this message in code i add resp.status_code and i got http error 404 but link is ok

ck is error ！

**Comment by AbyssMorgan** [comment]
Fixed, issue is in cookie file

1. Open netflix.com

2. Press ctrl + shift + I

3. Put in console for get variable value
```
netflix.appContext.state.model.models.serverDefs.data.BUILD_IDENTIFIER
```

4. Open configs/Cookies/cookies_nf.txt

5. Change value BUILD_IDENTIFIER

@Aijima

**Comment by gerberanub** [comment]
> Fixed, issue is in cookie file
> 
>     1. Open netflix.com
> 
>     2. Press ctrl + shift + I
> 
>     3. Put in console for get variable value
> 
> 
> ```
> netflix.appContext.state.model.models.serverDefs.data.BUILD_IDENTIFIER
> ```
> 
>     4. Open configs/Cookies/cookies_nf.txt
> 
>     5. Change value BUILD_IDENTIFIER
> 
> 
> [@Aijima](https://github.com/Aijima)

same  title is not available in your Netflix region.
